renaming master into main
CNERG/cnerg.github.com pull request #158
Opened 2020-06-18 21:17 UTC by bam241

this change all mentioned to master (branches or file name) into main

2020-07-21 00:36 UTC, opotowsky commented
Oh, looks like you did this already, @bam! I am trying to build it and not succeeding. Did you build successfully?

2020-07-21 01:54 UTC, bam241 commented
@opotowsky sorry I forgot about this :(

2020-07-21 01:55 UTC, bam241 commented
but I still can't change the branch that is used to deploy the website...

2020-07-21 16:22 UTC, opotowsky commented
True. Were you able to build locally? I'm getting a failure on it saying `main_doc` is undefined

2020-09-09 16:38 UTC, gonuke commented
One of the challenges with this kind of change is that some of them need to be properly imported into the `main` branch in parallel...

2020-09-09 16:46 UTC, gonuke requested changes
I think there is just one thing to confirm and we can merge this.  I've already flipped the bit on the repo to use the `main` branch for publishing

2020-09-09 16:46 UTC, gonuke commented on source/conf.py
> -master_doc = 'index'
not sure if we can change this - Sphinx may expect this variable to be set (although I'm not sure)

https://www.sphinx-doc.org/en/master/usage/configuration.html

2021-01-19 14:27 UTC, gonuke commented
This was effectively accomplished in move to new website.

2021-01-19 14:27 UTC, closed without merging