Alumni 2021
CNERG/cnerg.github.com pull request #191
Opened 2021-06-16 14:57 UTC by gonuke

Move folks to alumni status for Spring 2021

2021-06-17 17:31 UTC, gonuke commented on _data/people.yml
> +  - name: "Anna Caldwell-Overdier"
Probably not, then.  I copied it from its previous location... will update

2021-06-24 13:41 UTC, kkiesling requested changes
minor remaining comments now that I got to build this.

2021-06-24 13:41 UTC, kkiesling commented on _data/people.yml
> +    Role: MS
`role` is not appearing when built. I think it needs to be lowercase.
![nygaard](https://user-images.githubusercontent.com/4060017/123272649-8e8b3400-d4c7-11eb-9c3b-ee7b899da4ce.png)

2021-06-24 13:41 UTC, kkiesling commented on _layouts/people.html
> +          , <a href="{{ person.employer_url }}" target="_blank">{{ person.employer }}</a>
FYI- with this change, there is no comma in front of the company name if there is no url (see example of the two different behaviors)
![commas](https://user-images.githubusercontent.com/4060017/123272943-d5792980-d4c7-11eb-9766-4b82fd4822e1.png)

2021-07-22 15:38 UTC, kkiesling approved these changes
sorry, I forgot about this. lgtm.

2021-07-22 15:38 UTC, merged