Added Bowen
cnerg/cnerg.github.com pull request #199
Opened 2022-07-22 22:37 UTC by bquan0

2022-07-22 22:47 UTC, lewisgross1296 commented
@bquan0 Generally when you make a PR, you want to leave a description that explain the purpose so other reviewers know why it is being opened and what to look for when reviewing.

2022-07-22 23:41 UTC, gonuke requested changes
Thanks for this addition @bquan0 - it looks like there is an extra file.

2022-07-22 23:41 UTC, gonuke commented on community/people/bq/Bowen_Quan.jpg:Zone.Identifier
> +[ZoneTransfer]
I don't think this file should be here.  Not sure where it comes from.

2022-09-28 21:40 UTC, gonuke commented
Thanks @bquan0 - sorry this lingered so long!  You should feel free to nag me.

2022-09-28 21:40 UTC, gonuke approved these changes

2022-09-28 21:40 UTC, merged