Add myself
cnerg/cnerg.github.com pull request #211
Opened 2023-05-30 21:41 UTC by eitan-weinstein

2023-05-31 16:02 UTC, gonuke requested changes
Thanks for this contribution @eitan-weinstein - I have a couple of comments on the files here.  I think you'll also need to add yourself to the file `_data/people.yml` in the section that includes other undergraduates.

2023-05-31 16:02 UTC, gonuke commented on community/people/ew/docker
I don't think this file is necessary.

2023-05-31 16:02 UTC, gonuke commented on community/people/ew/index.md
> + "Eitan Weinstein is an undergraduate student at the University of Pennsylvania
I think you probably want to remove the quotation marks here.

2023-05-31 16:19 UTC, gonuke commented on community/people/ew/index.md
> + ---
I also discovered an extra space at the beginning of this line that will be a problem! Subtle bug

2023-05-31 16:55 UTC, eitan-weinstein commented
> Thanks for this contribution @eitan-weinstein - I have a couple of comments on the files here. I think you'll also need to add yourself to the file `_data/people.yml` in the section that includes other undergraduates.

It's possible I did this wrong, but when I went back in to add myself into the people.yml file, it looked like my initial addition was successful and I was seeing my entry there. I put myself right after Gerson's entry.

2023-05-31 17:03 UTC, eitan-weinstein commented
> > Thanks for this contribution @eitan-weinstein - I have a couple of comments on the files here. I think you'll also need to add yourself to the file `_data/people.yml` in the section that includes other undergraduates.
> 
> It's possible I did this wrong, but when I went back in to add myself into the people.yml file, it looked like my initial addition was successful and I was seeing my entry there. I put myself right after Gerson's entry.

Nevermind, I think I may have figured out the issue. I will submit another PR in a moment.

2023-06-01 00:17 UTC, gonuke requested changes
I think you managed to clear up the prior issues. Just one last request for a square (or nearly square) cropped image.  (Maybe we need to add that guidance to the how-to page as well.)

2023-06-01 00:17 UTC, gonuke commented on community/people/ew/EitanHeadshot.jpg
This looks a lot better, but one last issue - the photos are forced to be square on each person's page.  Can you crop this to a roughly square size?

2023-06-05 00:09 UTC, gonuke commented
This looks good now @eitan-weinstein! merging now

2023-06-05 00:09 UTC, gonuke approved these changes

2023-06-05 00:09 UTC, merged