Adding Micah Gale
cnerg/cnerg.github.com pull request #215
Opened 2023-09-03 18:04 UTC by MicahGale

Did a quick add of myself.

This will need clarification once I actually have a more concrete research topic.

2023-09-04 16:34 UTC, gonuke requested changes
Thanks for pulling this together @MicahGale - just one quick comment on the photo size.

2023-09-04 16:34 UTC, gonuke commented on community/people/mgale/DSC_4522.jpg
The template forces this to a square aspect ratio, so best to crop it to something nearly square.

2023-09-04 23:09 UTC, lewisgross1296 reviewed
This LGTM. One thing you may want to do to clean up the website commit history is an interactive rebase. If you've never done this before, essentially you squash all your changes into one commit. Locally, you'd
```
git rebase -i HEAD~N
```
where N is the number of commits that you'll squash together. It seems like here you'd do N=4. Once that is done, it will allow you to decide which commits to pick or squash and then you can add a description for the commit that will be in the history. 

Since you rebase locally and the commit history on the PR doesn't match your local commit history, you'll need to force push after (git push -f BRANCH). Feel free to slack me if this seems unclear.

2023-09-05 19:15 UTC, MicahGale commented on community/people/mgale/DSC_4522.jpg
Switched to a square crop with ff6bfeb3282.

2023-09-05 19:17 UTC, MicahGale commented
> 

Generally I am not a fan of rewriting history in git, and force pushes are generally not the solution.

However, given that I committed a jpg twice, and we aren't using LFS I'll squash to be nice to everyone else.

2023-09-05 19:24 UTC, MicahGale commented
I felt like being on the bleeding edge: so now this depends on #209, and should wait until that is merged first.

2023-09-06 15:00 UTC, gonuke commented
#209 should be ready for review/merge

2023-09-06 16:22 UTC, gonuke approved these changes

2023-09-09 20:52 UTC, gonuke commented
Does this need a rebase after merging #209?

2023-09-09 21:02 UTC, MicahGale commented
It seems github is ok with a simple merge. I'll do a quick merge locally just to be sure.

2023-09-09 21:15 UTC, gonuke commented
This looks great now.

2023-09-09 21:15 UTC, merged