Added Andrew Schumaker
cnerg/cnerg.github.com pull request #230
Opened 2023-12-05 16:25 UTC by inquisitor-schumaker

Added myself to the community folder.

2023-12-06 03:32 UTC, MicahGale requested changes

2023-12-06 03:32 UTC, MicahGale commented on community/people/aps/index.md
> +Andrew Schumaker (Shoe-maker) is a nuclear engineering graduate student at the University of Wisconsin-Madison. His undergraduate degree is in physics from the United States Military Academy, where h
1. Wisconsin —  Madison should use an em dash with spaces around the em dash.
2. Change "will be" to present tense.

2023-12-06 03:32 UTC, MicahGale commented on community/people/aps/index.md
> +city_state_zip: "Fitchburg, WI 53711"
Use your office location; not home location.

2023-12-06 03:32 UTC, MicahGale commented on community/people/aps/index.md
> +  github: inquisitor-schumaker
What, no X? :P

2023-12-06 03:40 UTC, MicahGale commented on community/people/aps/index.md
> +phone: "218/4608408"
Also including personal phone (I assume) is probably not necessary, but up to personal preference.

2023-12-07 17:48 UTC, MicahGale commented
I agree @gonuke, and thanks for doing the build because I deleted my build environment again.

2023-12-10 21:18 UTC, inquisitor-schumaker commented
Changes per request

2023-12-10 23:08 UTC, gonuke requested changes
Looks like you removed one line too many

2023-12-10 23:08 UTC, gonuke commented on community/people/aps/index.md
> +  github: inquisitor-schumaker
Your last change took out this necessary line

```suggestion
services:
  github: inquisitor-schumaker
```

2023-12-11 18:18 UTC, inquisitor-schumaker commented
Is the other line required? Whatever it was I removed I figured I didn't need since there was no useful information on it.

Respectfully,

Andrew Schumaker
Office: ERB 443
Email: ***@***.***
Campus ID: 9084958108
________________________________
From: Paul Wilson ***@***.***>
Sent: Sunday, December 10, 2023 5:08 PM
To: cnerg/cnerg.github.com ***@***.***>
Cc: Andrew Schumaker ***@***.***>; Author ***@***.***>
Subject: Re: [cnerg/cnerg.github.com] Added Andrew Schumaker (PR #230)


@gonuke requested changes on this pull request.

Looks like you removed one line too many

________________________________

In community/people/aps/index.md<https://github.com/cnerg/cnerg.github.com/pull/230#discussion_r1421834551>:

> @@ -0,0 +1,11 @@
+---
+layout: person
+title: Andrew Schumaker
+role: Graduate Student
+image: Andrew_Github.jpg
+email: ***@***.***
+city_state_zip: "443 ERB, Madison, WI"
+  github: inquisitor-schumaker


Your last change took out this necessary line

⬇️ Suggested change

-  github: inquisitor-schumaker
+services:
+  github: inquisitor-schumaker


—
Reply to this email directly, view it on GitHub<https://github.com/cnerg/cnerg.github.com/pull/230#pullrequestreview-1774116462>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BCDE5TTONCDQJXIX7D4RR2DYIY6GHAVCNFSM6AAAAABAH65UVWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTONZUGEYTMNBWGI>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-12-11 21:16 UTC, gonuke approved these changes
Welcome to CNERG!

2023-12-11 21:16 UTC, merged