modified people.yml
cnerg/cnerg.github.com pull request #235
Opened 2024-02-15 19:37 UTC by anu1217

Added self to people.yml document

2024-02-15 19:41 UTC, gonuke requested changes
Thanks for starting this update @anu1217 - please also make sure to include pages that describe you and the photo.

2024-02-15 19:41 UTC, gonuke commented on _data/people.yml
> +    image: asr.jpg
Probably want a blank line after this one.

2024-02-16 23:03 UTC, MicahGale reviewed
I think this just needs to be tested prior to deploying. 

@gonuke Do you not have a CI test build for the pedagogical value of learning docker?

2024-02-16 23:03 UTC, MicahGale commented on community/people/asr/index.md
> +    linkedin: anupama-rajendra-751371190
Do you have an ORCID?

2024-02-16 23:17 UTC, anu1217 commented on community/people/asr/index.md
> +    linkedin: anupama-rajendra-751371190
Added ORCID ID

2024-02-16 23:20 UTC, anu1217 commented
There is a test with docker in the instructions document - tried it and everything looks as intended.

2024-02-17 14:51 UTC, gonuke commented
> I think this just needs to be tested prior to deploying. 
> 
> 
> 
> @gonuke Do you not have a CI test build for the pedagogical value of learning docker?

Turns out to be non-trivial to do CI testing of Jekyl sites! I'd love to do testing, which would generally require posting some rendering of the site to some secret web location and then ensuring it is removed when done, etc... 

I'll have to see if anyone's come up with a reliable GitHub action for all that.

2024-02-17 16:14 UTC, gonuke approved these changes
Looks great @anu1217 !  Thanks for adding this.

2024-02-17 16:14 UTC, merged