Added Sarah attempt 2
cnerg/cnerg.github.com pull request #247
Opened 2024-08-06 23:22 UTC by trysarahtops

Updated sf people file

2024-08-07 15:00 UTC, gonuke commented
It looks like all the changes in #244 were correct, but were undone by your revert PR #245?  This PR is missing the changes to `_data/people.yml` again.

2024-08-07 22:33 UTC, lewisgross1296 commented
This is looking good again, but perhaps we should clean up the history with the revert? I don't think it hurts anyone to leave it though. @gonuke let us know your thoughts

2024-08-08 20:38 UTC, gonuke requested changes
I've tested this and remembered that the image is resized to a square aspect ratio on the personal page.  That means it's best to have an image that is close to square.  Thus, I recommend cropping the photo to be closer to square.

2024-08-09 20:28 UTC, trysarahtops commented
Made the image more square, tried to test and got an error.
```
sgfrancis@cnerg-docker-05:~/cnerg.github.com (add_myself) $ docker run --rm --volume="$PWD:/srv/jekyll" --volume="$PWD/vendor/bundle:/usr/local/bundle" -p 4000:4000  jekyll/jekyll  jekyll serve
docker: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Head "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
```

2024-08-09 20:29 UTC, gonuke requested changes
Thanks for updating the image - I think you need to update one more reference to that image

2024-08-09 20:29 UTC, gonuke commented on community/people/sf/index.md
> +image: Sarah.png
I think you'll need to update this for the new image filename, too

2024-08-09 20:30 UTC, gonuke commented
> Made the image more square, tried to test and got an error.
> 
> ```
> 
> sgfrancis@cnerg-docker-05:~/cnerg.github.com (add_myself) $ docker run --rm --volume="$PWD:/srv/jekyll" --volume="$PWD/vendor/bundle:/usr/local/bundle" -p 4000:4000  jekyll/jekyll  jekyll serve
> 
> docker: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Head "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied.
> 
> See 'docker run --help'.
> 
> ```

Have you run docker on this machine before?  I think there is a command that is needed before the first time, and I can't recall if you've done that before?

2024-08-09 20:41 UTC, trysarahtops commented
I entered  `cae-docker-setup`. It runs now but I got an error.
```
sgfrancis@cnerg-docker-05:~/cnerg.github.com (add_myself) $ docker run --rm --volume="$PWD:/srv/jekyll" --volume="$PWD/vendor/bundle:/usr/local/bundle" -p 4000:4000  jekyll/jekyll  jekyll serve
Unable to find image 'jekyll/jekyll:latest' locally
latest: Pulling from jekyll/jekyll
df9b9388f04a: Pull complete 
837e9cfc7e43: Pull complete 
c7850f1a8c23: Pull complete 
6ca4c39baa3d: Pull complete 
daa3a8cb79d3: Pull complete 
cf5821b9dd48: Pull complete 
Digest: sha256:400b8d1569f118bca8a3a09a25f32803b00a55d1ea241feaf5f904d66ca9c625
Status: Downloaded newer image for jekyll/jekyll:latest
chown: /usr/local/bundle: Operation not permitted
chown: /usr/local/bundle: Operation not permitted
There was an error while trying to write to `/usr/local/bundle/config`. It is
likely that you need to grant write permissions for that path. 
```

2024-08-09 20:45 UTC, gonuke commented
> I entered `cae-docker-setup`. It runs now but I got an error.
> 
> ```
> sgfrancis@cnerg-docker-05:~/cnerg.github.com (add_myself) $ docker run --rm --volume="$PWD:/srv/jekyll" --volume="$PWD/vendor/bundle:/usr/local/bundle" -p 4000:4000  jekyll/jekyll  jekyll serve
> Unable to find image 'jekyll/jekyll:latest' locally
> latest: Pulling from jekyll/jekyll
> df9b9388f04a: Pull complete 
> 837e9cfc7e43: Pull complete 
> c7850f1a8c23: Pull complete 
> 6ca4c39baa3d: Pull complete 
> daa3a8cb79d3: Pull complete 
> cf5821b9dd48: Pull complete 
> Digest: sha256:400b8d1569f118bca8a3a09a25f32803b00a55d1ea241feaf5f904d66ca9c625
> Status: Downloaded newer image for jekyll/jekyll:latest
> chown: /usr/local/bundle: Operation not permitted
> chown: /usr/local/bundle: Operation not permitted
> There was an error while trying to write to `/usr/local/bundle/config`. It is
> likely that you need to grant write permissions for that path. 
> ```

I'm not sure why you're getting that error ??  but maybe try without the second "--volume" command-line argument?

2024-08-09 20:45 UTC, gonuke commented
FWIW, the image is still a little distorted

2024-08-09 20:46 UTC, Edgar-21 commented
built locally, lgtm

2024-08-09 21:01 UTC, merged