Add projects
cnerg/cnerg.github.com pull request #266
Opened 2024-12-25 23:08 UTC by gonuke

This provides a basic but complete list of projects and a way to display them.

Future additions may include:
* [ ] reference to projects from CNERG member pages
* [ ] inclusion of references to publications from bib files
* [ ] reformatting of "area" pages to include projects

2025-01-15 19:55 UTC, Edgar-21 requested changes

2025-01-15 19:55 UTC, Edgar-21 commented on _data/areas.yml
>    desc: Open source software tools that allow flexible modeling of nuclear fuel cycles over varying time and physical fidelities.
None of the others have a period at the end
```suggestion
  desc: Open source software tools that allow flexible modeling of nuclear fuel cycles over varying time and physical fidelities
```

2025-01-15 19:55 UTC, Edgar-21 commented on _data/services.yml
> +  icon: instagram.svg
```suggestion
  icon: Instagram.svg
```

2025-01-15 19:57 UTC, Edgar-21 commented on _data/services.yml
> +  icon: instagram.svg
Website appears to be working how it should, so with these two little tweaks this lgtm. Not sure if we are waiting for the third checkbox to merge this?

2025-01-15 22:42 UTC, gonuke commented on _data/services.yml
> +  icon: instagram.svg
I changed the filename to be lower case

2025-01-16 21:32 UTC, Edgar-21 approved these changes

2025-01-16 21:33 UTC, merged